# Generated by Django 3.1.7 on 2021-02-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20210226_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='email',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
